import RiderEntity from "@/types/rider.type";

const mockRiders: RiderEntity[] = [
  {
    id: 1,
    riderID: "RDR-001",
    name: "John Doe",
    phoneNumber: "+2348012345678",
    email: "johndoe@example.com",
    status: "APPROVED",
    availabilityStatus: "ONLINE",
    bank_details: [],
    createdAt: new Date(),
    deletedAt: new Date(),
    deviceToken: "device_token_1",
    isApproved: true,
    isVerified: true,
    my_transaction: [],
    my_wallet: {
      id: 1,
      balance: 2500,
      createdAT: new Date(),
      updatedAT: new Date(),
      walletAddrress: "0x123wallet",
      isActive: true,
    },
    password: "hashed_password",
    profilePics: "https://randomuser.me/api/portraits/men/1.jpg",
    resetPasswordOtp: "123456",
    resetPasswordOtpExpiration: new Date(),
    role: "RIDER",
    updatedAt: new Date(),
  },
  {
    id: 2,
    riderID: "RDR-002",
    name: "Jane Smith",
    phoneNumber: "+2348098765432",
    email: "janesmith@example.com",
    status: "PENDING",
    availabilityStatus: "OFFLINE",
    bank_details: [],
    createdAt: new Date(),
    deletedAt: new Date(),
    deviceToken: "device_token_2",
    isApproved: false,
    isVerified: false,
    my_transaction: [],
    my_wallet: {
      id: 2,
      balance: 1000,
      createdAT: new Date(),
      updatedAT: new Date(),
      walletAddrress: "0x456wallet",
      isActive: false,
    },
    password: "hashed_password",
    profilePics: "https://randomuser.me/api/portraits/women/2.jpg",
    resetPasswordOtp: "654321",
    resetPasswordOtpExpiration: new Date(),
    role: "RIDER",
    updatedAt: new Date(),
  },
  {
    id: 3,
    riderID: "RDR-003",
    name: "Samuel Ade",
    phoneNumber: "+2348087654321",
    email: "samuelade@example.com",
    status: "DISABLED",
    availabilityStatus: "OFFLINE",
    bank_details: [],
    createdAt: new Date(),
    deletedAt: new Date(),
    deviceToken: "device_token_3",
    isApproved: true,
    isVerified: false,
    my_transaction: [],
    my_wallet: {
      id: 3,
      balance: 500,
      createdAT: new Date(),
      updatedAT: new Date(),
      walletAddrress: "0x789wallet",
      isActive: false,
    },
    password: "hashed_password",
    profilePics: "https://randomuser.me/api/portraits/men/3.jpg",
    resetPasswordOtp: "789012",
    resetPasswordOtpExpiration: new Date(),
    role: "RIDER",
    updatedAt: new Date(),
  },
];

export { mockRiders };
